### PR TITLE
Create MaitiuMorton.txt

### PR DESCRIPTION
**Pull request by Uitiam**
go fuck yourself

### CODE REVIEW

**Comment by Cyberfury66** [comment]
lol

**Comment by Cyberfury66** [comment]
How was your day today?

**Comment by Uitiam** [comment]
not bad had to work with a bunch of assholes

**Comment by Cyberfury66** [comment]
aw dude, that sounds like it sucks

**Comment by Cyberfury66** [comment]
the fuck is your feature?

**Comment by Uitiam** [comment]
NATHAN!!! I NEED SPACE!!

**Pull request merged**
